import { coreSemanticFeatures } from "./core-semantic.js";
import { audioFeatures } from "./domains/audio.js";
import { collaborationFeatures } from "./domains/collaboration.js";
import { colorFeatures } from "./domains/color.js";
import { effectsFeatures } from "./domains/effects.js";
import { exportFeatures } from "./domains/export.js";
import { mediaFeatures } from "./domains/media.js";
import { projectFeatures } from "./domains/project.js";
import { textFeatures } from "./domains/text.js";
import { thirdPartyFeatures } from "./domains/third-party.js";
import { timelineFeatures } from "./domains/timeline.js";
import { trimSyncMulticamFeatures } from "./domains/trim-sync-multicam.js";
import { workspaceFeatures } from "./domains/workspace.js";
import type { FeatureRegistryEntry } from "./registry-contract.js";
import { listActions } from "../catalog.js";

const roadmapEntries = [
  ...projectFeatures, ...mediaFeatures, ...timelineFeatures, ...trimSyncMulticamFeatures,
  ...effectsFeatures, ...audioFeatures, ...textFeatures, ...colorFeatures, ...exportFeatures,
  ...workspaceFeatures, ...collaborationFeatures, ...thirdPartyFeatures,
];

const coreById = new Map(coreSemanticFeatures.map((entry) => [entry.featureId, entry]));
const compareText = (left: string, right: string): number => left < right ? -1 : left > right ? 1 : 0;

function statusForAction(support: ReturnType<typeof listActions>[number]["support"]): FeatureRegistryEntry["status"] {
  if (support === "ui_fallback") return "UI_ADAPTER_REQUIRED";
  if (support === "entitlement_blocked") return "ENTITLEMENT_BLOCKED";
  if (support === "unsupported") return "UNSUPPORTED";
  if (support === "experimental") return "PREVIEW_ONLY";
  return "SUPPORTED_CONTEXTUAL";
}

export function listFeatureRegistry(): FeatureRegistryEntry[] {
  const merged = roadmapEntries.map((entry) => {
    const core = coreById.get(entry.featureId);
    if (!core) return structuredClone(entry);
    return {
      ...structuredClone(entry),
      title: core.title,
      status: core.status,
      backends: [...core.backends],
      risk: core.risk,
      minimumPremiereVersion: core.minimumPremiereVersion,
      maximumPremiereVersion: core.maximumPremiereVersion,
      preconditions: [...core.preconditions],
      verification: [...core.verification],
      fixture: core.fixture,
      limitations: [...core.limitations],
    };
  });
  const byId = new Map(merged.map((entry) => [entry.featureId, entry]));
  for (const action of listActions()) {
    const existing = byId.get(action.id);
    byId.set(action.id, {
      featureId: action.id,
      domain: existing?.domain ?? `public-${action.domain}`,
      title: existing?.title ?? action.title,
      status: statusForAction(action.support),
      backends: [...action.preferredBackends],
      risk: action.risk,
      minimumPremiereVersion: action.minimumPremiereVersion,
      maximumPremiereVersion: existing?.maximumPremiereVersion ?? null,
      preconditions: existing?.preconditions ?? [
        "connected host session",
        ...(action.stateTokenRequired ? [`matching ${action.stateScope ?? "scoped"} state token`] : []),
      ],
      verification: existing?.verification ?? [action.verification],
      fixture: existing?.fixture ?? null,
      limitations: existing?.limitations ?? ["Public action is registered from the catalog; live v0.3 evidence has not been recorded."],
    });
  }
  return [...byId.values()].sort((left, right) => compareText(left.featureId, right.featureId));
}

export function serializeFeatureRegistry(entries: readonly FeatureRegistryEntry[] = listFeatureRegistry()): string {
  return `${JSON.stringify(entries, null, 2)}\n`;
}

export function renderFeatureMatrix(entries: readonly FeatureRegistryEntry[] = listFeatureRegistry()): string {
  const statusCounts = new Map<string, number>();
  const domainCounts = new Map<string, number>();
  for (const entry of entries) {
    statusCounts.set(entry.status, (statusCounts.get(entry.status) ?? 0) + 1);
    domainCounts.set(entry.domain, (domainCounts.get(entry.domain) ?? 0) + 1);
  }
  const lines = [
    "# Premiere Feature Matrix", "",
    "Generated from `src/features/domains/*` plus the public action catalog projection. Do not edit this file manually.", "",
    `Registry entries: **${entries.length}**`, "",
    "No entry is marked verified without recorded live/runtime evidence. `SUPPORTED_CONTEXTUAL` means a typed implementation exists but still depends on host state and has no v0.3 live evidence.", "",
    "## Coverage by domain", "", "| Domain | Features |", "| --- | ---: |",
    ...[...domainCounts].sort(([a], [b]) => compareText(a, b)).map(([domain, count]) => `| ${domain} | ${count} |`),
    "", "## Coverage by state", "", "| State | Features |", "| --- | ---: |",
    ...[...statusCounts].sort(([a], [b]) => compareText(a, b)).map(([status, count]) => `| ${status} | ${count} |`),
    "", "## Registry", "", "| Feature | Domain | State | Backend path | Risk | Premiere versions | Preconditions | Verifier |", "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...entries.map((entry) => `| \`${entry.featureId}\` | ${entry.domain} | ${entry.status} | ${entry.backends.join(", ") || "none"} | ${entry.risk} | ${entry.minimumPremiereVersion ?? "unspecified"}–${entry.maximumPremiereVersion ?? "current"} | ${entry.preconditions.join("; ")} | ${entry.verification.join("; ")} |`),
    "",
  ];
  return lines.join("\n");
}
